name: raptor
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.9
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - filelock==3.18.0
    - fsspec==2025.5.0
    - hf-xet==1.1.2
    - huggingface-hub==0.32.0
    - idna==3.10
    - jinja2==3.1.6
    - joblib==1.5.1
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - nibabel==5.3.2
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - packaging==25.0
    - pandas==2.2.3
    - pillow==11.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.3
    - six==1.17.0
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tokenizers==0.21.1
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - tqdm==4.67.1
    - transformers==4.52.3
    - triton==3.2.0
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.4.0
